version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  web:
    build: .
    command: "rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./railsapp:/railsapp
    ports:
      - "3000:3000"
    depends_on:
      - db 